# User(id: integer, username: string, password_digest: string, email: string)
User.create(username: "Bruno", password: "1&Password", email: "brunogarciagonzalez@outlook.com")
User.create(username: "German", password: "2&Password", email: "germanjii@gmail.com")
# Tag(id: integer, title: string)
Tag.create(title:"Cannabis")
Tag.create(title:"Social Media")
Tag.create(title: "Features")
Tag.create(title: "Finance")
Tag.create(title: "Shopping")
Tag.create(title: "Jobs")
Tag.create(title: "Internet")
Tag.create(title: "Software")
Tag.create(title: "Programming")
Tag.create(title: "Computer Games")
Tag.create(title: "Console Games")
Tag.create(title: "Board Games")
Tag.create(title: "News")
Tag.create(title: "TV")
Tag.create(title: "Radio")
Tag.create(title: "Entertainment")
Tag.create(title: "Music")
Tag.create(title: "Movies")
Tag.create(title: "Recreational")
Tag.create(title: "Sports")
Tag.create(title: "Travel")
Tag.create(title: "Autos")
Tag.create(title: "Motorcycles")
Tag.create(title: "Outdoors")
Tag.create(title: "Health")
Tag.create(title: "Diseases")
Tag.create(title: "Drugs")
Tag.create(title: "Fitness")
Tag.create(title: "Government")
Tag.create(title: "Countries")
Tag.create(title: "People")
Tag.create(title: "Environment")
Tag.create(title: "Religion")
Tag.create(title: "College & University")
Tag.create(title: "Education: K - 12")
Tag.create(title: "Photography")
Tag.create(title: "History")
Tag.create(title: "Literature")
Tag.create(title: "Animals")
Tag.create(title: "Astronomy")
Tag.create(title: "Engineering")
Tag.create(title: "Languages")
Tag.create(title: "Archaeology")
Tag.create(title: "Psychology")
Tag.create(title: "Dictionaries")

Link.create(url: "https://www.x-cannabis.com")
Link.create(url: "https://www.google.com")
Link.create(url: "https://www.bing.com")

# UserShare 1:
UserShare.create(user_id: 1, review_id: 1, link_id: 1)
UserShareTagJoin.create(user_share_id: 1, tag_id: 7)
LinkTagJoin.create(link_id: 1, tag_id: 7)
Review.create(user_share_id: 1, reviewer_id: 1, link_id: 1, content: "I have been a member of this social network since its first days (roughly). It has upgraded much and with a more active community I look forward to where it goes. I will keep checking in as it grows and will update my review. I think it is a nice niche of a social network.", rating: 8)

# UserShare 2:
UserShare.create(user_id: 2, review_id: 2, link_id: 1)
Review.create(user_share_id: 2, reviewer_id: 2, link_id: 1, content: "test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test", rating: 2)
UserShareTagJoin.create(user_share_id: 2, tag_id: 7)


TagComment.create(tag_id: 1, tag_commenter_id: 2, content: "dope")
TagComment.create(tag_id: 1, tag_commenter_id: 1, content: "ganja")
ReviewComment.create(review_id: 1, review_commenter_id: 2, content: "Nice review.")
